version: '3.7'

networks:
  data:
    external: true

services:
  demoapp:
    image: localhost:32000/demoapp:v1-pcfens1
    # Uncomment the following 3 lines if you want to exec in to the container
    # command: sleep 3600
    # healthcheck:
    #   disable: true
    ports:
      - 8000:8080
      # - 1693:1693 # JMX listens here
    environment:
      CATALINA_OPTS: -Xmx2048M -Xms1024M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.awt.headless=true -Dfile.encoding=UTF-8
      DB_SCHEMA: app_db
      DB_USERNAME: app_user
      DB_PASSWORD: application_password
      DB_JDBC_STRING: jdbc:mysql://db:3306/app_db
      JMX_PORT: 1693
    networks:
      - data
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 3096M
          cpus: "1"
        reservations:
          memory: 1024M
          cpus: "1"
